### ISSUE TITLE
Erro no `xml` de Tramitações das Proposições

### ISSUE THREAD

**Issue by rodolfo-viana** [rodolfo-viana/novedejulho#12]
O `xml` com todas as Tramitações das Proposições possui algum erro de formatação e eu não consegui fazer um script pra ele.

https://www.al.sp.gov.br/dados-abertos/recurso/101

_Originally posted by @Vnicius in https://github.com/rodolfo-viana/novedejulho/pull/11#issuecomment-466672119_

**Comment by rodolfo-viana** [comment]
@cuducos, dê uma olhada na discussão deste PR do @Vnicius. Sabe como nos ajudar, por favor?

**Comment by cuducos** [comment]
Bom… pelo o que vi aqui, o XML está quebrado mesmo, tem tags se encerrando antes do que deveriam:

```console
$ xmllint documento_andamento.xml
documento_andamento.xml:192: parser error : Char 0x0 out of allowed range
                                                                               ^
documento_andamento.xml:192: parser error : Premature end of data in tag Descricao line 192
                                                                               ^
documento_andamento.xml:192: parser error : Premature end of data in tag DocumentoAndamento line 192
                                                                               ^
documento_andamento.xml:192: parser error : Premature end of data in tag documentos_andamentos line 1
```

Sendo assim, a única solução de verdade é corrigindo o XML mesmo; ou seja, utilizando o canal de contato da Assembleia, informando o erro e pedindo que eles corrijam. [Fizemos isso com a Câmara e funcionou](https://medium.com/data-science-brigade/mais-uma-mudan%C3%A7a-acidental-na-c%C3%A2mara-impacta-a-serenata-de-amor-ed3599545b80). Esse pedido vocês podem fazer inclusive pelo eSIC (se tiver) usando a LAI como argumento (devido ao erro, os dados não estão legíveis por máquinas, o que é garantido pela LAI — Lei nº 12.527/2011, art. 8º, § 3º, inciso III).

As outras “soluções” seriam gambiarras, mas quem nunca recorrei a uma boa e velha gambiarra, né? Vamos a algumas alternativas:

**Corrigir o XML**

Mal conseguimos abrir o arquivo (2.02Gb), então acho que essa alternativa eu listo só para constar. Se a gente tentar ler e entender o XML, ver o que está errado na sintaxe, podemos fazer um script para arrumar isso. O que eu tentaria: achar um auto-formatador de XML para ver se quebrando linhas e identando fica mais legível para humanos, usar o `xmllint` para ver em que parte/linha ocorre o erro, e aí identificar o que dá apra ser corrigido (e, depois automatizado).

**Pegando o que dá até o momento do erro**

Com o Python podemos _parsear_ um XML todo ou ir fazendo isso por partes. A vantagem de fazer por partes é que dá apra ler tudo até o ponto em que o arquivo tiver uma sintaxe válida. Olha um exemplo simples usando o [`xml.etree.ElementTree.iterparse`](https://docs.python.org/3.7/library/xml.etree.elementtree.html#xml.etree.ElementTree.iterparse):

<details>

```python
In [1]: from xml.etree.ElementTree import iterparse
In [2]: for index, element in enumerate(iterparse('documento_andamento.xml')):
   ...:     print(index, element)
   ...:

  (...)

1097233 ('end', <Element 'TpAndamento' at 0x11a28cef8>)
1097234 ('end', <Element 'DocumentoAndamento' at 0x11a28cbd8>)
1097235 ('end', <Element 'Descricao' at 0x11a28cf98>)
1097236 ('end', <Element 'Data' at 0x11a28e048>)
1097237 ('end', <Element 'IdComissao' at 0x11a28e0e8>)
1097238 ('end', <Element 'IdDocumento' at 0x11a28e138>)
1097239 ('end', <Element 'IdEtapa' at 0x11a28e188>)
1097240 ('end', <Element 'IdTpAndamento' at 0x11a28e1d8>)
1097241 ('end', <Element 'NmEtapa' at 0x11a28e228>)
1097242 ('end', <Element 'NrOrdem' at 0x11a28e278>)
1097243 ('end', <Element 'TpAndamento' at 0x11a28e2c8>)
1097244 ('end', <Element 'DocumentoAndamento' at 0x11a28cf48>)
1097245 ('end', <Element 'Descricao' at 0x11a28e368>)
1097246 ('end', <Element 'Data' at 0x11a28e3b8>)
1097247 ('end', <Element 'IdComissao' at 0x11a28e458>)
1097248 ('end', <Element 'IdDocumento' at 0x11a28e4a8>)
1097249 ('end', <Element 'IdEtapa' at 0x11a28e4f8>)
1097250 ('end', <Element 'IdTpAndamento' at 0x11a28e548>)
1097251 ('end', <Element 'NmEtapa' at 0x11a28e598>)
1097252 ('end', <Element 'NrOrdem' at 0x11a28e5e8>)
1097253 ('end', <Element 'TpAndamento' at 0x11a28e638>)
1097254 ('end', <Element 'DocumentoAndamento' at 0x11a28e318>)
Traceback (most recent call last):

  File "/usr/local/var/pyenv/versions/3.7.1/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3291, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-4-fa76dc55c1be>", line 1, in <module>
    for index, element in enumerate(iterparse('documento_andamento.xml')):

  File "/usr/local/var/pyenv/versions/3.7.1/lib/python3.7/xml/etree/ElementTree.py", line 1222, in iterator
    yield from pullparser.read_events()

  File "/usr/local/var/pyenv/versions/3.7.1/lib/python3.7/xml/etree/ElementTree.py", line 1297, in read_events
    raise event

  File "/usr/local/var/pyenv/versions/3.7.1/lib/python3.7/xml/etree/ElementTree.py", line 1269, in feed
    self._parser.feed(data)

  File "<string>", line unknown
ParseError: not well-formed (invalid token): line 192, column 421497
```

Repare que conseguimos acessar 1.097.254 (~1 milhão) de tags do XML. Não sei se é muito ou se é pouco, então não sei se é uma alternativa viável.
</details>

**Ignorando os erros**

Ao invés de um usar um parser de XML, uma estratégia é tentar _parsear_ como se fosse HTML — pois como existe muito HTML cagado no mundo, os _parsers_ de HTML costumam ser muito mais flexível e tolerantes a erros de sintaxe. Esse [post](https://chase-seibert.github.io/blog/2010/06/04/parsing-invalid-xml-with-beautiful-soup.html#) (e eu) recomenda o [`BeautifulSoup`](https://www.crummy.com/software/BeautifulSoup/).

Creio que nas tags onde tem os erros de sintaxe ainda exista perda de dados. Mas pelo menos podemos tentar extrair dados além desse ponto no arquivo ; )


---

E aí? Ajudei? Faz sentido?

**Comment by rodolfo-viana** [comment]
Ajudou demais, @cuducos, como sempre.

Vou abrir uma solicitação no eSIC e, com o número de protocolo, escrever para a Alesp pedindo o ajuste. (Eu tenho bom trânsito na assessoria de lá, o que deve ajudar.)

Enquanto isso, vou tentar parsear como HTML. Usamos BS4 no projeto, então não será uma biblioteca a mais a pesar na porra toda. Vamos ver no que dá. :)

Valeuzão.

(Eu vou deixar essa issue aberta para publicar atualizações do rolê.)
